
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Aug 03 22:00:42 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated interface containing symbol constants. */
public interface Isym {
  /* terminals */
  public static final int perc = 24;
  public static final int plusplus = 34;
  public static final int lbracket = 43;
  public static final int PRINT_K = 18;
  public static final int CASE_K = 11;
  public static final int mul = 22;
  public static final int VOID_K = 7;
  public static final int IF_K = 8;
  public static final int ELSE_K = 9;
  public static final int plus = 20;
  public static final int lbrace = 39;
  public static final int neq = 26;
  public static final int NEW_K = 17;
  public static final int CONST_K = 6;
  public static final int minus = 21;
  public static final int gt = 27;
  public static final int rbrace = 40;
  public static final int qmark = 45;
  public static final int comma = 37;
  public static final int CLASS_K = 3;
  public static final int int_lit = 47;
  public static final int EXTENDS_K = 5;
  public static final int CONTINUE_K = 13;
  public static final int leq = 30;
  public static final int ENUM_K = 4;
  public static final int READ_K = 19;
  public static final int EOF = 0;
  public static final int ident = 50;
  public static final int rbracket = 44;
  public static final int RETURN_K = 14;
  public static final int error = 1;
  public static final int lt = 29;
  public static final int or = 32;
  public static final int colon = 46;
  public static final int lparen = 41;
  public static final int bool_lit = 48;
  public static final int rparen = 42;
  public static final int minusminus = 35;
  public static final int SWITCH_K = 10;
  public static final int WHILE_K = 16;
  public static final int BREAK_K = 12;
  public static final int and = 31;
  public static final int semicol = 36;
  public static final int eq = 25;
  public static final int PROGRAM_K = 2;
  public static final int char_lit = 49;
  public static final int assign = 33;
  public static final int div = 23;
  public static final int geq = 28;
  public static final int dot = 38;
  public static final int DO_K = 15;
}

