//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated interface containing symbol constants (terminals). */
public class sym {
    // utility symbols
    public static final int EOF              = 0;
    public static final int error            = 1;
 // public static final int EOF_RULE         = 2;
 // public static final int NO_ACTION        = 3;
 // public static final int LOOK_AHEAD       = 4;
 // public static final int WHITESPACE       = 5;

    // keywords
    public static final int K_PROGRAM        = 10;
    public static final int K_CLASS          = 11;
    public static final int K_ENUM           = 12;
    public static final int K_EXTENDS        = 13;

    public static final int K_CONST          = 14;
    public static final int K_VOID           = 15;
    public static final int K_INT            = 16;
    public static final int K_BOOL           = 17;
    public static final int K_CHAR           = 18;

    public static final int K_IF             = 19;
    public static final int K_ELSE           = 20;
    public static final int K_SWITCH         = 21;
    public static final int K_CASE           = 22;
    public static final int K_DEFAULT        = 23;
    public static final int K_BREAK          = 24;
    public static final int K_CONTINUE       = 25;
    public static final int K_RETURN         = 26;

    public static final int K_DO             = 27;
    public static final int K_WHILE          = 28;

    public static final int K_NEW            = 29;
    public static final int K_PRINT          = 30;
    public static final int K_READ           = 31;

    // operators
    public static final int O_PLUS           = 40;
    public static final int O_MINUS          = 41;
    public static final int O_MUL            = 42;
    public static final int O_DIV            = 43;
    public static final int O_PERC           = 44;

    public static final int O_EQUAL          = 45;
    public static final int O_NOT_EQUAL      = 46;
    public static final int O_GREAT          = 47;
    public static final int O_GREAT_EQUALS   = 48;
    public static final int O_LESS           = 49;
    public static final int O_LESS_EQUALS    = 50;
    public static final int O_AND            = 51;
    public static final int O_OR             = 52;

    public static final int O_ASSIGN         = 53;
    public static final int O_PLUS_PLUS      = 54;
    public static final int O_MINUS_MINUS    = 55;

    public static final int O_SEMICOLON      = 56;
    public static final int O_COMMA          = 57;
    public static final int O_DOT            = 58;
    public static final int O_PAREN_OPEN     = 59;
    public static final int O_PAREN_CLOSE    = 60;
    public static final int O_BRACKET_OPEN   = 61;
    public static final int O_BRACKET_CLOSE  = 62;
    public static final int O_BRACE_OPEN     = 63;
    public static final int O_BRACE_CLOSE    = 64;
    public static final int O_QUESTION_MARK  = 65;
    public static final int O_COLON          = 66;

    // constants
    public static final int C_INT            = 90;
    public static final int C_BOOL           = 91;
    public static final int C_CHAR           = 92;
    
    // identifiers
    public static final int IDENTIFIER       = 100;


    public static String getSymbolName( int symbol_id )
    {
        return symbol_names[ symbol_id ];
    }

    private static final String[] symbol_names = {
        // utility symbols
        "EOF",             // 0
        "error",           // 1
        "EOF_RULE",        // 2
        "NO_ACTION",       // 3
        "LOOK_AHEAD",      // 4
        "WHITESPACE",      // 5

        "--reserved--",    // 6
        "--reserved--",    // 7
        "--reserved--",    // 8
        "--reserved--",    // 9

        // keywords
        "K_PROGRAM",       // 10
        "K_CLASS",         // 11
        "K_ENUM",          // 12
        "K_EXTENDS",       // 13

        "K_CONST",         // 14
        "K_VOID",          // 15
        "K_INT",           // 16
        "K_BOOL",          // 17
        "K_CHAR",          // 18

        "K_IF",            // 19
        "K_ELSE",          // 20
        "K_SWITCH",        // 21
        "K_CASE",          // 22
        "K_DEFAULT",       // 23
        "K_BREAK",         // 24
        "K_CONTINUE",      // 25
        "K_RETURN",        // 26

        "K_DO",            // 27
        "K_WHILE",         // 28

        "K_NEW",           // 29
        "K_PRINT",         // 30
        "K_READ",          // 31

        "--reserved--",    // 32
        "--reserved--",    // 33
        "--reserved--",    // 34
        "--reserved--",    // 35
        "--reserved--",    // 36
        "--reserved--",    // 37
        "--reserved--",    // 38
        "--reserved--",    // 39
        
        // operators
        "O_PLUS",          // 40
        "O_MINUS",         // 41
        "O_MUL",           // 42
        "O_DIV",           // 43
        "O_PERC",          // 44

        "O_EQUAL",         // 45
        "O_NOT_EQUAL",     // 46
        "O_GREAT",         // 47
        "O_GREAT_EQUALS",  // 48
        "O_LESS",          // 49
        "O_LESS_EQUALS",   // 50
        "O_AND",           // 51
        "O_OR",            // 52

        "O_ASSIGN",        // 53
        "O_PLUS_PLUS",     // 54
        "O_MINUS_MINUS",   // 55

        "O_SEMICOLON",     // 56
        "O_COMMA",         // 57
        "O_DOT",           // 58
        "O_PAREN_OPEN",    // 59
        "O_PAREN_CLOSE",   // 60
        "O_BRACKET_OPEN",  // 61
        "O_BRACKET_CLOSE", // 62
        "O_BRACE_OPEN",    // 63
        "O_BRACE_CLOSE",   // 64
        "O_QUESTION_MARK", // 65
        "O_COLON",         // 66

        "--reserved--",    // 67
        "--reserved--",    // 68
        "--reserved--",    // 69
        
        "--reserved--",    // 70
        "--reserved--",    // 71
        "--reserved--",    // 72
        "--reserved--",    // 73
        "--reserved--",    // 74
        "--reserved--",    // 75
        "--reserved--",    // 76
        "--reserved--",    // 77
        "--reserved--",    // 78
        "--reserved--",    // 79
        
        "--reserved--",    // 80
        "--reserved--",    // 81
        "--reserved--",    // 82
        "--reserved--",    // 83
        "--reserved--",    // 84
        "--reserved--",    // 85
        "--reserved--",    // 86
        "--reserved--",    // 87
        "--reserved--",    // 88
        "--reserved--",    // 89

        // constants
        "C_INT",           // 90
        "C_BOOL",          // 91
        "C_CHAR",          // 92
        
        "--reserved--",    // 93
        "--reserved--",    // 94
        "--reserved--",    // 95
        "--reserved--",    // 96
        "--reserved--",    // 97
        "--reserved--",    // 98
        "--reserved--",    // 99
        
        
        // identifiers
        "IDENTIFIER",      // 100
    };
}

