//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated interface containing symbol constants (terminals). */
public class sym {
    // utility symbols
    public static final int EOF              = 0;
    public static final int error            = 1;
 // public static final int EOF_RULE         = 2;
 // public static final int NO_ACTION        = 3;
 // public static final int LOOK_AHEAD       = 4;
 // public static final int WHITESPACE       = 5;

    // keywords
    public static final int K_PROGRAM        = 10;
    public static final int K_CLASS          = 11;
    public static final int K_ENUM           = 12;
    public static final int K_EXTENDS        = 13;

    public static final int K_CONST          = 14;
    public static final int K_VOID           = 15;
    public static final int K_INT            = 16;
    public static final int K_BOOL           = 17;
    public static final int K_CHAR           = 18;

    public static final int K_IF             = 19;
    public static final int K_ELSE           = 20;
    public static final int K_SWITCH         = 21;
    public static final int K_CASE           = 22;
    public static final int K_DEFAULT        = 23;
    public static final int K_BREAK          = 24;
    public static final int K_CONTINUE       = 25;
    public static final int K_RETURN         = 26;

    public static final int K_DO             = 27;
    public static final int K_WHILE          = 28;

    public static final int K_NEW            = 29;
    public static final int K_PRINT          = 30;
    public static final int K_READ           = 31;

    // operators
    public static final int O_PLUS           = 40;
    public static final int O_MINUS          = 41;
    public static final int O_MUL            = 42;
    public static final int O_DIV            = 43;
    public static final int O_PERC           = 44;

    public static final int O_EQUAL          = 45;
    public static final int O_NOT_EQUAL      = 46;
    public static final int O_GREAT          = 47;
    public static final int O_GREAT_EQUALS   = 48;
    public static final int O_LESS           = 49;
    public static final int O_LESS_EQUALS    = 50;
    public static final int O_AND            = 51;
    public static final int O_OR             = 52;

    public static final int O_ASSIGN         = 53;
    public static final int O_PLUS_PLUS      = 54;
    public static final int O_MINUS_MINUS    = 55;

    public static final int O_SEMICOLON      = 56;
    public static final int O_COMMA          = 57;
    public static final int O_DOT            = 58;
    public static final int O_PAREN_OPEN     = 59;
    public static final int O_PAREN_CLOSE    = 60;
    public static final int O_BRACKET_OPEN   = 61;
    public static final int O_BRACKET_CLOSE  = 62;
    public static final int O_BRACE_OPEN     = 63;
    public static final int O_BRACE_CLOSE    = 64;
    public static final int O_QUESTION_MARK  = 65;
    public static final int O_COLON          = 66;

    // constants
    public static final int C_INT            = 90;
    public static final int C_BOOL           = 91;
    public static final int C_CHAR           = 92;
    
    // identifiers
    public static final int IDENTIFIER       = 100;
}

